project:
  type: website

website:
  title: "exogamy.1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - morphology.qmd
    right:
      - icon: github
        href: https://github.com/seldenlab/exogamy.1
        aria-label: GitHub

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

