---
title: "Can exogamy be inferred from arrow points? A case study from the American Southeast"
author:
  - name: Robert Z. Selden, Jr.
    affiliations:
      - Heritage Research Center, Stephen F. Austin State University; Department of Biology, Stephen F. Austin State University; Texas Archeological Research Laboratory, The University of Texas at Austin; and Cultural Heritage Department, Jean Monnet University
    email: zselden@sfasu.edu
    orcid: 0000-0002-1789-8449
bibliography: [exogamy.bib]
date: "`r format(Sys.time(), '%d %B, %Y')`"
link-citations: yes
github-repo: seldenlab/exogamy.1
---

>“The question of questions for mankind—the problem which underlies all others, and is more deeply interesting than any other—is the ascertainment of the place which man occupies in nature, and of his relation to the universe of things.” **–H. Thomas Henry Huxley**, _Man’s Place in Nature_

# Hypothesis

The Caddo division of labor suggests that---generally---men were the manufacturers of lithic tools and arrow points, which is supported by the ethnographic literature, and if the material/s in each (individual; not group) burial were _personal property_ and not _offerings_—also supported by the ethnographic literature—then the null hypothesis (H0) would be that males adopted the knapping traditions/idiosyncrasies of their new community, while another (H1) would be that they retained the knapping traditions/idiosyncrasies associated with their natal community. Support for the null hypothesis is expected in instances where arrow points from individual burials in a community were largely homogenous; alternatively, the inverse would provide support for H1.
