---
title: "Morphology by Burial"
---

## Load packages + data

```{r load.packages.burial, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
#devtools::install_github("MomX/Momocs")
library(here)
library(Momocs)

# read images
jpg.list <- list.files("stemmed.burial", 
                       full.names = TRUE)

# read attribute data
att.data <- read.csv("stemmed.csv", 
                     header = TRUE, 
                     as.is = TRUE)

# attribute to factor
att.data$burial <- as.factor(att.data$burial)
att.data$site <- as.factor(att.data$site)
```

## Generate outlines

```{r outlines + attributes.burial, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_center()
```

## Calibrate harmonic + EFA

```{r cal.harm.burial, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# generate efa outlines
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 23,
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.burial, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# plot pca by burial
plot_PCA(pca.outlines, 
         morphospace_position = "xy",
         palette = pal_qual_solarized,
         chullfilled = TRUE,
         ~burial,
         labelgroups = TRUE,
         legend = FALSE,
         axesnames = TRUE,
         morphospace = TRUE,
         eigen = TRUE,
         box = FALSE,
         zoom = 0.7)

# mean shape + 2sd for the first 2 pcs
PCcontrib(pca.outlines, nax = 1:2)
```

## MANOVA

```{r manova.burial, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# shape difference between burials?
MANOVA(pca.outlines, 'burial')

# which differ?
MANOVA_PW(pca.outlines, 'burial')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
## characterise shape diffs by significant results
# mean shapes for F2.2072/F2.2073
ms.1 <- MSHAPES(efa.outlines, ~burial, nb.pts = 100)$shp
F2.2072 <- ms.1$F2.2072
F2.2073 <- ms.1$F2.2073
tps_iso(F2.2073, F2.2072, iso.nb = 1000, grid = TRUE, legend = FALSE)
tps_arr(F2.2073, F2.2072, arr.nb = 200, grid = TRUE, legend = FALSE)
tps_grid(F2.2073, F2.2072, grid.size = 50)

# mean shapes for F2.2073/F8.1091
F8.1091 <- ms.1$F8.1091
tps_iso(F2.2073, F8.1091, iso.nb = 1000, grid = TRUE, legend = FALSE)
tps_arr(F2.2073, F8.1091, arr.nb = 200, grid = TRUE, legend = FALSE)
tps_grid(F2.2073, F8.1091, grid.size = 50)
```
